spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  profiles:
    active: '@environment@'
  mail:
    host: smtp.163.com
    username: 19382099605@163.com
    password: QPqRB34rGvpfnKHX