spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username:
    password:
  data:
    redis:
      host:
      port: 6379
      database:
server:
  port: 8080
