spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ku_test
    username: root
    password: ZXL52O1314
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: KnowledgeUniverse@163.com
    password: PFh5wPrgiYyYtubG
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
server:
  port: 8080
  servlet:
    session:
      timeout: 86400s
